return {
    id = "pistol",
    displayName = "PISTOL",
    viewmodelPrefab = "Assets/Prefabs/PistolViewmodel.prefab",
    fireSound = "Assets/Audio/Weapons/rifle.wav",
    magSize = 12,
    startingReserve = 48,
    practiceReserve = 999,
    reloadTime = 1.25,
    fireInterval = 0.22,
    damage = 25,
    range = 100.0,
    hipFov = 90.0,
    adsFov = 72.0,
    hipSide = 0.27,
    adsSide = 0.035,
    hipForward = 0.56,
    adsForward = 0.62,
    hipDown = -0.20,
    adsDown = -0.14,
    cameraKick = 0.010,
    viewKick = 0.045,
    kickRecovery = 6.0,
    recoilRiseSpeed = 12.0,
    recoilReturnSpeed = 7.0
}
