return {
    id = "rifle",
    displayName = "KESTREL / CARBINE",
    viewmodelPrefab = "Assets/Prefabs/RifleViewmodel.prefab",
    fireSound = "Assets/Audio/Breakbulk/carbine.wav",
    magSize = 30,
    startingReserve = 90,
    practiceReserve = 999,
    reloadTime = 1.55,
    fireInterval = 0.11,
    damage = 20,
    range = 140.0,
    hipFov = 90.0,
    adsFov = 68.0,
    hipSide = 0.34,
    adsSide = 0.055,
    hipForward = 0.62,
    adsForward = 0.70,
    hipDown = -0.24,
    adsDown = -0.18,
    cameraKick = 0.018,
    viewKick = 0.065,
    kickRecovery = 7.5
}
